export const VM_WATCH_CHANGE = "vmWatchChange"
export const VM_BREAKPOINT = "vmBreakpoint"
export const VM_COMMAND_FAILED = "vmCommandFailed"
export const VM_ROLE_MISSING = "vmRoleMissing"
export const VM_GLOBAL_CHANGE = "vmVariableChange"
export const VM_GLOBAL_TYPE_MISMATCH = "vmDynamicTypeError"
export const VM_INTERNAL_ERROR = "vmInternalError"
export const VM_LOG_ENTRY = "vmLogEntry"
