name: MakeCode

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache npm and makecode
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.pxt/mkc-cache
          key: ${{ runner.os }}-${{ hashFiles('pxt.json') }}-${{ hashFiles('mkc*json') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: npm install
        run: |
          npm install -g makecode
      - run: makecode -u -j --mono-repo -c mkc.json
      - run: makecode -u -j --mono-repo -c mkc-maker.json
      - run: makecode -u -j --mono-repo -c mkc-arcade.json
      - run: makecode -c mkc.json
      - run: makecode -c mkc-maker.json
      - run: makecode -c mkc-arcade.json --hw F4,D5,N4,N3
      - run: cd tools/multitool && makecode --hw F4,D5,N4,N3
      - name: Upload UF2
        uses: actions/upload-artifact@v1
        with:
          name: multitool-f4-d5-n4.uf2
          path: tools/multitool/built/combined.uf2
      - name: Upload HEX
        uses: actions/upload-artifact@v1
        with:
          name: multitool-microbit.hex
          path: tools/multitool/built/n3/binary.hex
